---
permalink: online-help/concept-how-group-rules-work-for-groups.html 
sidebar: sidebar 
keywords:  
summary: 'Una regla de grupo es un criterio que se define para habilitar la inclusión de objetos de almacenamiento \(volúmenes, clústeres o SVM\) en un grupo específico. Puede utilizar grupos de condiciones o condiciones para definir reglas de grupo para un grupo.' 
---
= Cómo funcionan las reglas de grupo para los grupos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una regla de grupo es un criterio que se define para habilitar los objetos de almacenamiento (volúmenes, clústeres o SVM) que se incluirán en un grupo específico. Puede utilizar grupos de condiciones o condiciones para definir reglas de grupo para un grupo.

* Debe asociar una regla de grupo a un grupo.
* Debe asociar un tipo de objeto para una regla de grupo; sólo hay un tipo de objeto asociado a una regla de grupo.
* Los objetos de almacenamiento se agregan o eliminan del grupo después de cada ciclo de supervisión o cuando se crea, edita o elimina una regla.
* Una regla de grupo puede tener uno o más grupos de condiciones y cada grupo de condiciones puede tener una o más condiciones.
* Los objetos de almacenamiento pueden pertenecer a varios grupos según las reglas de grupo que cree.




== Condiciones

Puede crear varios grupos de condiciones y cada grupo de condiciones puede tener una o más condiciones. Puede aplicar todos los grupos de condiciones definidos en una regla de grupo para los grupos con el fin de especificar qué objetos de almacenamiento se incluyen en el grupo.

Las condiciones dentro de un grupo de condiciones se ejecutan utilizando lógica Y. Deben cumplirse todas las condiciones de un grupo de condiciones. Al crear o modificar una regla de grupo, se crea una condición que aplica, selecciona y agrupa sólo los objetos de almacenamiento que cumplen todas las condiciones del grupo de condiciones. Puede utilizar varias condiciones dentro de un grupo de condiciones cuando desee limitar el ámbito de los objetos de almacenamiento que se incluirán en un grupo.

Puede crear condiciones con objetos de almacenamiento mediante las operaciones y el operador siguientes y especificando el valor requerido.

|===
| Tipo de objeto de almacenamiento | Operandos aplicables 


 a| 
Volumen
 a| 
* Nombre del objeto
* Propietario del nombre del clúster
* Nombre de SVM propietario
* Anotaciones




 a| 
SVM
 a| 
* Nombre del objeto
* Propietario del nombre del clúster
* Anotaciones




 a| 
Clúster
 a| 
* Nombre del objeto
* Anotaciones


|===
Cuando se selecciona anotación como operando para cualquier objeto de almacenamiento, el operador "'is'" está disponible. Para el resto de operandos, puede seleccionar "'is'" o "'contains'" como operador.

* Operando
+
La lista de operandos en Unified Manager cambia según el tipo de objeto seleccionado. La lista incluye el nombre del objeto, el nombre del clúster propietario, el nombre de SVM propietario y las anotaciones que defina en Unified Manager.

* Operador
+
La lista de operadores cambia según el operando seleccionado para una condición. Los operadores admitidos en Unified Manager son «'is'» y «'contains».

+
Cuando se selecciona el operador "'is'", la condición se evalúa para la coincidencia exacta del valor de operando con el valor proporcionado para el operando seleccionado.

+
Al seleccionar el operador "'contains'", la condición se evalúa para cumplir uno de los siguientes criterios:

+
** El valor de operando es una coincidencia exacta con el valor proporcionado para el operando seleccionado
** El valor de operando contiene el valor proporcionado para el operando seleccionado


* Valor
+
El campo valor cambia según el operando seleccionado.





== Ejemplo de una regla de grupo con condiciones

Considere un grupo de condiciones para un volumen con las dos condiciones siguientes:

* El nombre contiene «'vol'»
* El nombre de SVM es «data_svm».


Este grupo de condiciones selecciona todos los volúmenes que incluyen «'vol'» en sus nombres y que están alojados en las SVM con el nombre «dATA_svm».



== Grupos de condiciones

Los grupos de condiciones se ejecutan mediante lógico O y, a continuación, se aplican a los objetos de almacenamiento. Los objetos de almacenamiento deben satisfacer uno de los grupos de condición que se incluirán en un grupo. Se combinan los objetos de almacenamiento de todos los grupos de condiciones. Puede utilizar grupos de condiciones para aumentar el alcance de los objetos de almacenamiento que se incluirán en un grupo.



== Ejemplo de una regla de grupo con grupos de condiciones

Debe tener en cuenta dos grupos de condiciones para un volumen, con cada grupo que contiene las dos condiciones siguientes:

* Grupo de condición 1
+
** El nombre contiene «'vol'»
** El nombre de SVM es «data_svm» el grupo de condiciones 1 selecciona todos los volúmenes que incluyen «'vol» en sus nombres y que están alojados en las SVM con el nombre «data_svm».


* Grupo de condiciones 2
+
** El nombre contiene «'vol'»
** El valor de anotación de la prioridad de datos es el grupo de condiciones «'crítico'» 2 selecciona todos los volúmenes que incluyen «'vol'» en sus nombres y que se anotan con el valor de anotación de prioridad de datos como «'crítico'».




Cuando se aplica una regla de grupo que contiene estos dos grupos de condiciones a los objetos de almacenamiento, se agregan los siguientes objetos de almacenamiento a un grupo seleccionado:

* Todos los volúmenes que incluyan «'vol» en sus nombres y que estén alojados en la SVM con el nombre «data_svm».
* Todos los volúmenes que incluyan «'vol'» en sus nombres y que estén anotados con el valor de anotación de prioridad de datos «'crítico'».

