---
permalink: online-help/concept-how-scripts-work-with-alerts.html 
sidebar: sidebar 
keywords:  
summary: Es posible asociar una alerta a la secuencia de comandos para que se ejecute el script cuando se genera una alerta para un evento en Unified Manager. Puede usar los scripts para resolver problemas con objetos de almacenamiento o identificar qué objetos de almacenamiento generan los eventos. 
---
= Cómo funcionan los scripts con alertas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible asociar una alerta a la secuencia de comandos para que se ejecute el script cuando se genera una alerta para un evento en Unified Manager. Puede usar los scripts para resolver problemas con objetos de almacenamiento o identificar qué objetos de almacenamiento generan los eventos.

Cuando se genera una alerta para un evento en Unified Manager, se envía un correo electrónico de alerta a los destinatarios especificados. Si asoció una alerta a un script, se ejecuta el script. Puede obtener los detalles de los argumentos pasados al script desde el correo electrónico de alerta.

El script utiliza los siguientes argumentos para su ejecución:

* -`eventID`
* -`eventName`
* -`eventSeverity`
* -`eventSourceID`
* -`eventSourceName`
* -`eventSourceType`
* -`eventState`
* -`eventArgs`


Puede utilizar los argumentos de las secuencias de comandos y recopilar información de eventos relacionada o modificar objetos de almacenamiento.



== Ejemplo para obtener argumentos de scripts

[listing]
----
print "$ARGV[0] : $ARGV[1]\n"
print "$ARGV[7] : $ARGV[8]\n"
----
Cuando se genera una alerta, se ejecuta este script y se muestra el siguiente resultado:

[listing]
----
-eventID : 290
-eventSourceID : 4138
----