---
permalink: online-help/concept-guidelines-for-adding-alerts.html 
sidebar: sidebar 
keywords:  
summary: Puede añadir alertas basadas en un recurso, como un clúster, nodo, agregado o volumen, y eventos de un tipo de gravedad determinado. Como práctica recomendada, puede añadir una alerta para cualquiera de los objetos críticos después de haber agregado el clúster al que pertenece el objeto. 
---
= Directrices para añadir alertas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede añadir alertas basadas en un recurso, como un clúster, nodo, agregado o volumen, y eventos de un tipo de gravedad determinado. Como práctica recomendada, puede añadir una alerta para cualquiera de los objetos críticos después de haber agregado el clúster al que pertenece el objeto.

Puede utilizar las siguientes directrices y consideraciones para crear alertas y gestionar los sistemas de forma eficaz:

* Descripción de alertas
+
Debe proporcionar una descripción de la alerta para ayudarle a realizar un seguimiento de las alertas de forma eficaz.

* Recursos
+
Debe decidir qué recurso físico o lógico requiere una alerta. Puede incluir y excluir recursos, según sea necesario. Por ejemplo, si desea supervisar de cerca los agregados mediante la configuración de una alerta, debe seleccionar los agregados necesarios de la lista de recursos.

* Gravedad del evento
+
Debe decidir si un evento de un tipo de gravedad especificado (crítico, error, advertencia) debe activar la alerta y, de ser así, qué tipo de gravedad.

* Nombre del evento
+
Si añade una alerta según el tipo de evento generado, debe decidir qué eventos requieren una alerta

* Acciones
+
Debe indicar los nombres de usuario y las direcciones de correo electrónico de los usuarios que reciben la notificación. También puede especificar una captura SNMP como un modo de notificación. Puede asociar los scripts a una alerta para que se ejecuten cuando se genere una alerta.

* Frecuencia de notificación
+
Puede configurar una alerta para que envíe repetidamente notificaciones a los destinatarios durante un tiempo específico. Debe determinar la hora desde la cual está activa la notificación de eventos para la alerta. Si desea que la notificación de eventos se repita hasta que se reconozca el evento, debe determinar la frecuencia con la que desea que se repita la notificación.

* Ejecutar secuencia de comandos
+
Puede asociar la secuencia de comandos con una alerta. La secuencia de comandos se ejecuta cuando se genera la alerta.


