---
permalink: online-help/reference-reverse-resync-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Cuando tiene una relación de protección rota debido a que el volumen de origen está deshabilitado y el destino se hace un volumen de lectura/escritura, la resincronización inversa permite invertir la dirección de la relación de modo que el destino se convierta en el nuevo origen y el origen se convierta en el nuevo destino. 
---
= Cuadro de diálogo Reverse Resync
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando tiene una relación de protección rota debido a que el volumen de origen está deshabilitado y el destino se hace un volumen de lectura/escritura, la resincronización inversa permite invertir la dirección de la relación de modo que el destino se convierta en el nuevo origen y el origen se convierta en el nuevo destino.

Cuando un desastre deshabilita el volumen de origen en la relación de protección, se puede usar el volumen de destino para suministrar datos mediante la conversión a lectura/escritura, mientras se repara o sustituye el origen, se actualiza el origen y se establece la relación. Cuando realiza una operación de resincronización inversa, se eliminan los datos del origen más nuevos que los de la copia común de Snapshot.



== Antes de realizar una resincronización inversa

Muestra el origen y el destino de una relación antes de una operación de resincronización inversa.

* *Volumen de origen*
+
El nombre y la ubicación del volumen de origen antes de una operación de resincronización inversa .

* *Volumen de destino*
+
El nombre y la ubicación del volumen de destino antes de una operación de resincronización inversa .





== Tras realizar una resincronización inversa

Muestra el origen y el destino de una relación después de una operación de resincronización de reserva.

* *Volumen de origen*
+
El nombre y la ubicación del volumen de origen después de una operación de resincronización inversa.

* *Volumen de destino*
+
El nombre y la ubicación del volumen de destino después de una operación de resincronización inversa.





== Botones de comando

Los botones de comando le permiten realizar las siguientes acciones:

* *Enviar*
+
Inicia el proceso de resincronización inversa.

* *Cancelar*
+
Cierra el cuadro de diálogo Reverse Resync sin iniciar una operación de resincronización inversa.


