---
permalink: online-help/reference-identity-provider-requirements-um.html 
sidebar: sidebar 
keywords:  
summary: 'Al configurar Unified Manager para utilizar un proveedor de identidades \(IDP\) para realizar la autenticación SAML de todos los usuarios remotos, debe tener en cuenta algunos ajustes de configuración necesarios para que la conexión a Unified Manager se realice correctamente.' 
---
= Requisitos del proveedor de identidades
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al configurar Unified Manager para que utilice un proveedor de identidades (IDP) para realizar la autenticación SAML de todos los usuarios remotos, debe tener en cuenta algunos ajustes de configuración necesarios para que la conexión a Unified Manager se haya realizado correctamente.

Debe introducir el URI y los metadatos de Unified Manager en el servidor IDP. Puede copiar esta información desde la página autenticación de Unified Manager SAML. Unified Manager se considera el proveedor de servicios (SP) en el estándar de lenguaje de marcado de aserción de seguridad (SAML).



== Estándares de cifrado compatibles

* Estándar de cifrado avanzado (AES): AES-128 y AES-256
* Secure Hash Algorithm (SHA): SHA-1 y SHA-256




== Proveedores de identidades validados

* Shibboleth
* Servicios de Federación de Active Directory (ADFS).




== Requisitos de configuración de ADFS

* Debe definir tres reglas de reclamación en el siguiente orden que se requieren para que Unified Manager analice las respuestas SAML de ADFS para esta entrada de confianza de parte confiable.
+
|===
| Regla de reclamación | Valor 


 a| 
SAM-account-name
 a| 
ID del nombre



 a| 
SAM-account-name
 a| 
urn:oid:0.9.2342.19200300.100.1.1



 a| 
Grupos de token -- Nombre no cualificado
 a| 
urn:oid:1.3.6.1.4.1.5923.1.5.1.1

|===
* Debe establecer el método de autenticación en "'autenticación de formularios'" o puede que los usuarios reciban un error al cerrar sesión en Unified Manager cuando utilicen Internet Explorer. Siga estos pasos:
+
.. Abra la Consola de administración de ADFS.
.. Haga clic en la carpeta Directivas de autenticación de la vista de árbol izquierda.
.. En acciones a la derecha, haga clic en Editar directiva de autenticación primaria global.
.. Establezca el método de autenticación de la intranet en "'autenticación de formularios'" en lugar del valor predeterminado "'autenticación de Windows'".


* En algunos casos, se rechaza iniciar sesión mediante el IDP cuando el certificado de seguridad de Unified Manager está firmado por CA. Existen dos soluciones alternativas para resolver este problema:
+
** Siga las instrucciones identificadas en el vínculo para deshabilitar la comprobación de revocación en el servidor ADFS para la parte de confianza asociada al certificado de CA encadenada:
+
http://www.torivar.com/2016/03/22/adfs-3-0-disable-revocation-check-windows-2012-r2/[]

** Haga que el servidor de CA resida en el servidor ADFS para firmar la solicitud de certificado del servidor Unified Manager.






== Otros requisitos de configuración

* La desviación del reloj de Unified Manager se establece en 5 minutos, por lo que la diferencia de hora entre el servidor IDP y el servidor Unified Manager no puede ser superior a 5 minutos o se producirá un error en la autenticación.
* Cuando los usuarios intentan acceder a Unified Manager mediante Internet Explorer, es posible que vean el mensaje *el sitio web no puede mostrar la página*. Si esto ocurre, asegúrese de que estos usuarios desmarcaran la opción de "mensajes de error HTTP fáciles de usar" en *Herramientas* > *Opciones de Internet* > *Avanzado*.

