---
permalink: online-help/reference-edit-rule-advanced-edit-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Puede utilizar el cuadro de diálogo Editar regla para editar las propiedades de una regla que no se crea mediante una plantilla. Las propiedades de regla que puede editar incluyen los tipos de archivo, las rutas de acceso de directorio, los criterios coincidentes o los propietarios. Puede seleccionar una clase de almacenamiento adecuada para la regla. Por ejemplo, puede editar las condiciones especificadas en los criterios coincidentes de una regla. 
---
= Cuadro de diálogo Edit Rule (edición avanzada)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el cuadro de diálogo Editar regla para editar las propiedades de una regla que no se crea mediante una plantilla. Las propiedades de regla que puede editar incluyen los tipos de archivo, las rutas de acceso de directorio, los criterios coincidentes o los propietarios. Puede seleccionar una clase de almacenamiento adecuada para la regla. Por ejemplo, puede editar las condiciones especificadas en los criterios coincidentes de una regla.



== Nombre de regla

Muestra el nombre de la regla.



== Criterios de coincidencia

Muestra una lista de condiciones relacionadas con la plantilla de regla seleccionada. La lista de condiciones cambia según la plantilla de regla seleccionada. Puede expandir las reglas y modificar las propiedades de la regla según sea necesario.



== Área de colocación de contenido

Muestra la lista de clases de almacenamiento. Puede seleccionar una clase de almacenamiento adecuada para la regla seleccionada.



== Botones de comando

* *Actualizar*
+
Actualiza los cambios realizados en la regla y cierra el cuadro de diálogo Editar regla.

* *Cancelar*
+
Cancela los cambios recientes realizados en la regla y cierra el cuadro de diálogo Editar regla.


