---
permalink: online-help/reference-storage-vm-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: Utilice la página Performance/SVM Information para ver una lista de los atributos configurados de la SVM. Esta información puede ayudar a responder preguntas relacionadas con el rendimiento. 
---
= Página Performance/SVM Information
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice la página Performance/SVM Information para ver una lista de los atributos configurados de la SVM. Esta información puede ayudar a responder preguntas relacionadas con el rendimiento.



== Atributos de SVM

* *Dirección IP*
+
Si está definida, esta es la dirección IPv4 o IPv6 de la LIF de gestión de SVM.

* *Espacio IP*
+
El espacio IP en el que reside esta SVM.

* *Nombre de dominio*
+
El nombre de dominio completo (FQDN) de la LIF de gestión de SVM.

* *Tipo de servicio*
+
El tipo de SVM.

+
Los posibles valores incluyen: «'Admin» para la SVM de gestión en todo el clúster, «System» para las comunicaciones a nivel de clúster en un espacio IP, «deata» para servicios de datos SVM y «'Node» para la SVM de gestión de nodos.

* *Capacidad (libre/total)*
+
El almacenamiento total disponible para el SVM, en gigabytes y la cantidad de almacenamiento disponible actualmente.

* *Cluster*
+
El nombre del clúster al que pertenece la SVM. Puede hacer clic en el nombre para mostrar los detalles del clúster en la página Performance/Cluster Explorer.

* *Volúmenes*
+
La cantidad de volúmenes en la SVM. Puede hacer clic en el número para mostrar los volúmenes en la página Performance/Volume Inventory.

* *LIF*
+
El número de LIF disponibles para la SVM. Puede hacer clic en el número para mostrar las LIF en la página Performance/LIF Inventory.

* *LIF de datos*
+
El número y el tipo de LIF de datos disponibles para la SVM.

* *Tipo de volumen permitido*
+
El tipo de volumen que se puede crear en la SVM.

+
Las instancias de SVM pueden contener uno o más volúmenes de FlexVol o FlexGroup. Se permite el tipo de FlexGroup cuando se usa ONTAP 9.1 o posterior.

+
[NOTE]
====
Las páginas de rendimiento de Unified Manager no admiten volúmenes infinitos.

====
* *Protocolos permitidos*
+
La lista de todos los protocolos que puede servir esta SVM. Los protocolos disponibles son FC/FCoE, iSCSI, HTTP, NDMP, NVMe, NFS y CIFS.

* *Conjunto de puertos*
+
Si se define para los protocolos FCP o iSCSI, el conjunto de puertos asignado a esta SVM.


