---
permalink: online-help/task-aborting-an-active-data-protection-transfer-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: Puede anular una transferencia de protección de datos activa cuando desee detener una replicación de SnapMirror en curso. También puede borrar el punto de control de reinicio para una transferencia si no es una transferencia de línea base. Puede cancelar una transferencia cuando entra en conflicto con otra operación, como un movimiento de volumen. 
---
= Cancelar una transferencia de protección de datos activa desde la página de detalles Estado/volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede anular una transferencia de protección de datos activa cuando desee detener una replicación de SnapMirror en curso. También puede borrar el punto de control de reinicio para una transferencia si no es una transferencia de línea base. Puede cancelar una transferencia cuando entra en conflicto con otra operación, como un movimiento de volumen.



== Antes de empezar

* Debe tener el rol de administrador de OnCommand o de administrador del almacenamiento.
* Debe haber configurado Workflow Automation.




== Acerca de esta tarea

La acción Anular no se muestra en las siguientes instancias:

* Si la configuración de RBAC no permite esta acción: Por ejemplo, si solo tiene privilegios de operador
* Cuando se desconoce el ID de volumen: Por ejemplo, cuando se mantiene una relación de interconexión de clústeres y el clúster de destino aún no se detectó


No puede borrar el punto de comprobación de reinicio para una transferencia de línea de base.



== Pasos

. En la pestaña *Protección* de la página de detalles *Estado/volumen*, haga clic con el botón derecho del ratón en la relación en la vista de topología para la transferencia de datos que desea cancelar y seleccione *Anular*.
+
Aparecerá el cuadro de diálogo Anular transferencia .

. Si desea borrar el punto de comprobación de reinicio para una transferencia que no sea una transferencia de línea de base, seleccione *Borrar puntos de control*.
. Haga clic en *continuar*.
+
El cuadro de diálogo Anular transferencia se cierra y el estado de la operación de anulación se muestra en la parte superior de la página de detalles Estado/volumen junto con un enlace a los detalles del trabajo.

. Haga clic en el enlace *Ver detalles* para ir a la página de detalles *Protección/Trabajo* para obtener más detalles y ver el progreso del trabajo.
. Haga clic en cada tarea de trabajo para ver sus detalles.
. Haga clic en la flecha Atrás de su navegador para volver a la página de detalles *Health/Volume*.
+
La operación de anulación finaliza cuando todas las tareas de trabajo se completan correctamente.


