---
permalink: online-help/task-editing-protection-relationships-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: Es posible editar las relaciones de protección existentes para cambiar la tasa de transferencia máxima actual, la política de protección o la programación de protección. Se puede editar una relación para reducir el ancho de banda que se usa para las transferencias o aumentar la frecuencia de las transferencias programadas, ya que los datos cambian con frecuencia. 
---
= Editar las relaciones de protección en la página de detalles Health/Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible editar las relaciones de protección existentes para cambiar la tasa de transferencia máxima actual, la política de protección o la programación de protección. Se puede editar una relación para reducir el ancho de banda que se usa para las transferencias o aumentar la frecuencia de las transferencias programadas, ya que los datos cambian con frecuencia.



== Antes de empezar

* Debe tener el rol de administrador de OnCommand o de administrador del almacenamiento.
* Debe haber instalado y configurado Workflow Automation.




== Acerca de esta tarea

Los volúmenes seleccionados deben ser destinos de relaciones de protección. No puede editar las relaciones cuando se seleccionan los volúmenes de origen, los volúmenes compartidos de carga o los volúmenes que no son el destino de una relación de SnapMirror o SnapVault.



== Pasos

. En la pestaña *Protección* de la página de detalles *Estado/volumen*, busque en la topología la relación de protección que desea editar y haga clic con el botón derecho del ratón en ella.
. Seleccione *Editar* en el menú.
+
Como alternativa, en el menú *acciones*, seleccione *relación* > *Edición* para editar la relación para la que está viendo los detalles.

+
Se muestra el cuadro de diálogo Editar relación.

. En el cuadro de diálogo *Editar relación*, edite la tasa de transferencia máxima, la política de protección o el programa de protección según sea necesario.
. Haga clic en *aplicar*.
+
Los cambios se aplican a las relaciones seleccionadas.


