---
permalink: online-help/task-editing-clusters.html 
sidebar: sidebar 
keywords:  
summary: Es posible modificar la configuración de un clúster existente, como el nombre de host o la dirección IP, el nombre de usuario, la contraseña, el protocolo y el puerto. Mediante el cuadro de diálogo Edit Cluster. 
---
= Editar clústeres
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible modificar la configuración de un clúster existente, como el nombre de host o la dirección IP, el nombre de usuario, la contraseña, el protocolo y el puerto. Mediante el cuadro de diálogo Edit Cluster.



== Antes de empezar

Debe tener el rol de administrador de OnCommand o de administrador del almacenamiento.



== Acerca de esta tarea

[NOTE]
====
Si cambia la dirección IP de un clúster a una dirección IP de un clúster supervisado existente, se pierden todos los datos del clúster existente cuando se detecta el primer clúster. No se muestra un mensaje de error para advertirle.

====


== Pasos

. En el panel de navegación de la izquierda, haga clic en *Configuración* > *fuentes de datos de clúster*.
. En la página *orígenes de datos de configuración/clúster*, seleccione el clúster que desea editar y, a continuación, haga clic en *Editar*.
. En el cuadro de diálogo *Editar clúster*, modifique los valores según sea necesario.
. Haga clic en *Enviar*.

