---
permalink: online-help/task-monitoring-jobs.html 
sidebar: sidebar 
keywords:  
summary: Puede utilizar la página Protection/Jobs para supervisar el estado del trabajo y para ver propiedades del trabajo, como el tipo de servicio de almacenamiento, el estado, el tiempo de envío y el tiempo de finalización, a fin de determinar si un trabajo se ha completado correctamente o no. 
---
= Supervisar trabajos de
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar la página Protection/Jobs para supervisar el estado del trabajo y para ver propiedades del trabajo, como el tipo de servicio de almacenamiento, el estado, el tiempo de envío y el tiempo de finalización, a fin de determinar si un trabajo se ha completado correctamente o no.



== Antes de empezar

Debe tener el rol de administrador de OnCommand o de administrador del almacenamiento.



== Pasos

. En el panel de navegación izquierdo, haga clic en *Protección* > *trabajos*.
+
Aparece la página Protection/Jobs.

. Consulte la columna *Estado* para determinar el estado de los trabajos que se están ejecutando actualmente.
. Haga clic en un nombre de trabajo para ver los detalles de ese trabajo en particular.
+
Se muestra la página de detalles Protection/Job.


