---
permalink: online-help/task-quiescing-a-protection-relationship-from-the-volume-relationships-page.html 
sidebar: sidebar 
keywords:  
summary: En la página Protection/Volume Relationships, es posible desactivar una relación de protección para evitar temporalmente las transferencias de datos. Puede desactivar una relación cuando desea crear una copia Snapshot de un volumen de destino de SnapMirror que contiene una base de datos, y desea garantizar que su contenido sea estable durante la operación de copia de Snapshot. 
---
= Desactivación de una relación de protección en la página Protection/Volume Relationships
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En la página Protection/Volume Relationships, es posible desactivar una relación de protección para evitar temporalmente las transferencias de datos. Puede desactivar una relación cuando desea crear una copia Snapshot de un volumen de destino de SnapMirror que contiene una base de datos, y desea garantizar que su contenido sea estable durante la operación de copia de Snapshot.



== Antes de empezar

* Debe tener el rol de administrador de OnCommand o de administrador del almacenamiento.
* Debe haber configurado Workflow Automation.




== Acerca de esta tarea

La acción de inactividad no se muestra en las siguientes instancias:

* Si la configuración de RBAC no permite esta acción; por ejemplo, si solo tiene privilegios de operador
* Cuando se desconoce el ID de volumen; por ejemplo, cuando se establece una relación de interconexión de clústeres y el clúster de destino aún no se detectó
* Cuando no esté emparejado Workflow Automation y Unified Manager




== Pasos

. Para desactivar las transferencias para una o más relaciones de protección, en la página *Relaciones de volumen/Protección*, seleccione uno o más volúmenes y, en la barra de herramientas, haga clic en *Quiesce*.
+
Aparecerá el cuadro de diálogo Quiesce.

. Haga clic en *continuar*.
+
El estado del trabajo en modo inactivo se muestra en la parte superior de la página de detalles Health/Volume, junto con un enlace a los detalles del trabajo.

. Haga clic en el enlace *Ver detalles* para ir a la página de detalles *Protección/Trabajo* para obtener más detalles y progreso del trabajo.
. Haga clic en la flecha *Atrás* de su explorador para volver a la página *Relaciones de volumen/Protección*.
+
El trabajo de inactividad finaliza cuando todas las tareas de trabajo se completan correctamente.


