---
permalink: online-help/task-moving-workloads-to-a-node-in-a-different-ha-pair.html 
sidebar: sidebar 
keywords:  
summary: 'Puede utilizar Unified Manager para ayudar a identificar un agregado en un nodo en una pareja \(ha\) de alta disponibilidad que tiene más capacidad de rendimiento libre que la pareja de alta disponibilidad donde se ejecutan actualmente las cargas de trabajo. A continuación, puede mover los volúmenes seleccionados a agregados en la nueva pareja de ha.' 
---
= Mover cargas de trabajo a un nodo en un par de alta disponibilidad diferente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar Unified Manager para ayudar a identificar un agregado en un nodo en una pareja de alta disponibilidad (ha) diferente con más capacidad de rendimiento libre que la pareja de alta disponibilidad en la que se ejecutan actualmente las cargas de trabajo. A continuación, puede mover los volúmenes seleccionados a agregados en la nueva pareja de ha.



== Antes de empezar

* Debe tener el rol de operador, administrador de OnCommand o administrador del almacenamiento.
* Su clúster debe estar formado por un mínimo de dos parejas de alta disponibilidad
+
No puede utilizar este proceso de corrección si solo tiene un par de alta disponibilidad en su clúster.

* Debe haber registrado los nombres de los dos nodos de la pareja de ha que están teniendo actualmente un problema de rendimiento.
* Debe haber registrado la fecha y la hora en que los nodos recibieron el evento de rendimiento.
* Debe haber registrado el ID del evento, por ejemplo, «'p-sdt-clus1-nod-6982».
* Unified Manager debe haber recopilado y analizado los datos de rendimiento por un mes o más.




== Acerca de esta tarea

Mover cargas de trabajo de alto rendimiento a un agregado en un nodo con una capacidad de rendimiento más libre permite que las cargas de trabajo de ambos nodos tengan un rendimiento más eficiente. Este procedimiento le ayuda a identificar los siguientes recursos para que pueda mover cargas de trabajo de alto rendimiento a un nodo con más capacidad de rendimiento libre en un par de alta disponibilidad diferente:

* Los nodos de una pareja de alta disponibilidad diferente en el mismo clúster que tienen la mayor capacidad de rendimiento libre
* Los agregados de los nuevos nodos con la mayor capacidad de rendimiento libre
* Los volúmenes de mayor rendimiento en los nodos actuales




== Pasos

. Identifique los nodos que forman parte de una pareja de alta disponibilidad diferente en el mismo clúster:
+
.. En la página *Detalles de evento*, haga clic en el nombre del clúster en el que residen los nodos.
+
Los detalles del clúster se muestran en la página Performance/Cluster Landing.

.. En la página *Resumen*, haga clic en *nodos* en el panel *objetos gestionados*.
+
La lista de nodos de este clúster se muestra en la página Performance/Nodes.

.. Escriba los nombres de los nodos que están en parejas de ha diferentes de la pareja de ha que tiene actualmente un problema de rendimiento.


. Identifique un nodo en la nueva pareja de alta disponibilidad que tenga la mayor capacidad de rendimiento libre:
+
.. En la página *Performance/Nodes*, haga clic en la columna *Performance Capacity used* para ordenar los nodos por el porcentaje mínimo utilizado.
+
Proporciona una lista de nodos potenciales a los que se podría mover cargas de trabajo.

.. Escriba el nombre del nodo en un par de alta disponibilidad diferente al que desea mover las cargas de trabajo.


. Identifique un agregado en el nodo nuevo que tenga la mayor capacidad de rendimiento libre:
+
.. En la página *Performance/Nodes*, haga clic en el nodo.
+
Los detalles del nodo se muestran en la página Performance/Node Explorer.

.. En el menú *Ver y comparar*, seleccione *agregados en este nodo*.
+
Los agregados de este nodo se muestran en la cuadrícula.

.. Haga clic en la columna *capacidad de rendimiento utilizada* para ordenar los agregados por menos utilizados.
+
De este modo, se proporciona una lista de agregados potenciales a los que se pueden mover cargas de trabajo.

.. Escriba el nombre del agregado al que desea mover las cargas de trabajo.


. Identifique las cargas de trabajo de alto rendimiento desde los nodos que recibieron el evento:
+
.. Vuelva a la página de detalles *evento* del evento.
.. En el campo *volúmenes afectados*, haga clic en el enlace del número de volúmenes del primer nodo.
+
La página Performance/Volumes se muestra con una lista filtrada de los volúmenes de ese nodo.

.. Haga clic en la columna *capacidad total* para ordenar los volúmenes por el espacio asignado más grande.
+
Proporciona una lista de los volúmenes potenciales que se pueden mover.

.. Escriba los nombres de los volúmenes que desea mover y los nombres de los agregados actuales en los que residen.
.. Realice los pasos 4c y 4d para el segundo nodo que formaba parte de este evento para identificar los volúmenes posibles que desea mover también desde ese nodo.


. Mueva los volúmenes a los agregados que ha identificado como con la mayor capacidad de rendimiento libre del nuevo nodo.
+
Puede llevar a cabo la operación de transferencia con System Manager de OnCommand, OnCommand Workflow Automation, comandos de ONTAP o una combinación de estas herramientas.





== Después de terminar

Tras unos días, puede comprobar si está recibiendo el mismo tipo de eventos de este nodo o agregado.
