---
permalink: online-help/task-identifying-shark-workloads-involved-in-a-performance-event.html 
sidebar: sidebar 
keywords:  
summary: En Unified Manager, es posible identificar qué cargas de trabajo tienen la mayor desviación de uso para un componente de almacenamiento en contención. La identificación de estas cargas de trabajo le ayuda a determinar si estas cargas de trabajo se deben mover a un clúster menos utilizado. 
---
= Identificar cargas de trabajo de tiburón involucradas en un evento de rendimiento dinámico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En Unified Manager, es posible identificar qué cargas de trabajo tienen la mayor desviación de uso para un componente de almacenamiento en contención. La identificación de estas cargas de trabajo le ayuda a determinar si estas cargas de trabajo se deben mover a un clúster menos utilizado.



== Antes de empezar

* Debe tener el rol de operador, administrador de OnCommand o administrador del almacenamiento.
* Hay un evento dinámico de rendimiento nuevo, reconocido o obsoleto.




== Acerca de esta tarea

La página de detalles Event muestra una lista de las cargas de trabajo definidas por el usuario y definidas por el sistema con la clasificación del uso más alto del componente o más afectado por el evento. Los valores se basan en los picos identificados por Unified Manager cuando detectó y analizó por última vez el evento.



== Pasos

. Abra la página *Detalles del evento* para ver información sobre el evento.
. En los gráficos Workload Latency y Workload Activity, seleccione *Shark Workloads*.
. Pase el cursor por los gráficos para ver las principales cargas de trabajo definidas por el usuario que afectan al componente y el nombre de la carga de trabajo de tiburón.

