---
settings:
  name: OnCommand Unified Manager 9.5
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de OnCommand Unified Manager 9.5
    url: "/index.html"
  - title: Notas de la versión
    url: "/release-notes.html"
  - title: Manos a la obra
    entries:
    - title: Instalación rápida para VMware vSphere
      url: "/qsg-vapp.html"
    - title: Instalación de inicio rápido para Linux
      url: "/qsg-linux.html"
    - title: Instalación de inicio rápido para Windows
      url: "/qsg-windows.html"
  - section: install
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - title: Avisos legales
    url: "/legal-notices.html"
