---
permalink: health-checker/task-changing-the-maintenance-user-password-on-windows.html 
sidebar: sidebar 
keywords:  
summary: Es posible cambiar la contraseña de usuario de mantenimiento de Unified Manager si es necesario. 
---
= Cambiar la contraseña del usuario de mantenimiento en Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible cambiar la contraseña de usuario de mantenimiento de Unified Manager si es necesario.



== Pasos

. En la página de inicio de sesión de la interfaz de usuario web de Unified Manager, haga clic en *Contraseña olvidada*.
+
Aparece una página que solicita el nombre del usuario cuya contraseña desea restablecer.

. Introduzca el nombre de usuario y haga clic en *Enviar*.
+
Se envía un correo electrónico con un enlace para restablecer la contraseña a la dirección de correo electrónico definida para ese nombre de usuario.

. Haga clic en el enlace *restablecer contraseña* del correo electrónico y defina la nueva contraseña.
. Vuelva a la interfaz de usuario web e inicie sesión en Unified Manager con la nueva contraseña.




== Después de terminar

Si Unified Manager está instalado en un entorno Microsoft Cluster Server (MSCS), debe cambiar la contraseña de usuario de mantenimiento en el segundo nodo de la configuración MSCS. La contraseña de usuario de mantenimiento para ambos nodos debe ser la misma.
