---
permalink: health-checker/task-accessing-rest-apis-using-the-swagger-api-web-page-ocum.html 
sidebar: sidebar 
keywords:  
summary: Las API DE REST se exponen a través de la página web de Swagger. Es posible acceder a la página web de Swagger para ver la documentación de la API DE REST de Unified Manager, y también para emitir manualmente una llamada API. 
---
= Acceder a API DE REST a través de la página web de API de Swagger
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las API DE REST se exponen a través de la página web de Swagger. Es posible acceder a la página web de Swagger para ver la documentación de la API DE REST de Unified Manager, y también para emitir manualmente una llamada API.



== Antes de empezar

* Debe tener uno de los siguientes roles: Operador, administrador de almacenamiento o administrador de OnCommand.
* Debe conocer la dirección IP o el nombre de dominio completo del servidor de Unified Manager donde desea ejecutar las API DE REST.




== Acerca de esta tarea

Se proporciona un ejemplo para cada API REST en la página web de Swagger para ayudar a explicar los objetos y atributos que puede utilizar para mostrar la información que está interesado en revisar.



== Pasos

. Acceda a las API de REST de Unified Manager.
+
|===
| Opción | Descripción 


 a| 
Desde la interfaz de usuario web de Unified Manager:
 a| 
En la barra de menús, haga clic en el botón *Ayuda* y seleccione *Documentación de API*.



 a| 
Desde la ventana del navegador:
 a| 
Utilice la dirección IP del servidor de Unified Manager o el FQDN para acceder a la página API DE REST en formato `https://<Unified_Manager_IP_address_or_name>/apidocs/`. Por ejemplo: `+https://10.10.10.10/apidocs/+`

|===
+
Se muestra una lista de los tipos de recursos o categorías de la API.

. Haga clic en un tipo de recurso de la API para mostrar las API en ese tipo de recurso.

