---
permalink: health-checker/task-changing-the-umadmin-password-on-rhel.html 
sidebar: sidebar 
keywords:  
summary: Por motivos de seguridad, debe cambiar la contraseña predeterminada del usuario umadmin de Unified Manager inmediatamente después de completar el proceso de instalación. Si es necesario, puede cambiar la contraseña de nuevo en cualquier momento. 
---
= Cambiar la contraseña de umadmin en sistemas Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Por motivos de seguridad, debe cambiar la contraseña predeterminada del usuario umadmin de Unified Manager inmediatamente después de completar el proceso de instalación. Si es necesario, puede cambiar la contraseña de nuevo en cualquier momento.



== Antes de empezar

* Unified Manager debe estar instalado en un sistema Red Hat Enterprise Linux o CentOS de Linux.
* Debe tener las credenciales de usuario raíz del sistema Linux en el que está instalado Unified Manager.




== Pasos

. Inicie sesión como usuario raíz en el sistema Linux en el que está ejecutando Unified Manager.
. Cambiar la contraseña de umadmin: `passwd umadmin`
+
El sistema le pide que introduzca una nueva contraseña para el usuario umadmin.





== Después de terminar

Si Unified Manager está instalado en un entorno de VERITAS Cluster Server (VCS), deberá cambiar la contraseña umadmin en el segundo nodo de la configuración del VCS. La contraseña umadmin para ambos nodos debe ser la misma.
