---
permalink: health-checker/task-configuring-global-volume-health-threshold-values.html 
sidebar: sidebar 
keywords:  
summary: Puede configurar los valores de umbral de estado global para todos los volúmenes para realizar un seguimiento de cualquier incumplimiento de umbral. Se generan eventos apropiados para las infracciones de los umbrales de salud y puede tomar medidas preventivas basadas en estos eventos. Puede configurar los valores globales a partir de la configuración de prácticas recomendadas para los umbrales que se aplican a todos los volúmenes supervisados. 
---
= Configurar los valores de umbral de estado de volúmenes globales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar los valores de umbral de estado global para todos los volúmenes para realizar un seguimiento de cualquier incumplimiento de umbral. Se generan eventos apropiados para las infracciones de los umbrales de salud y puede tomar medidas preventivas basadas en estos eventos. Puede configurar los valores globales a partir de la configuración de prácticas recomendadas para los umbrales que se aplican a todos los volúmenes supervisados.



== Antes de empezar

Debe tener el rol de administrador de OnCommand o de administrador del almacenamiento.



== Acerca de esta tarea

La mayoría de las opciones de umbral tienen valores predeterminados para una mejor supervisión. Sin embargo, puede cambiar los valores para adaptarlos a los requisitos de su entorno.

Tenga en cuenta que cuando se habilita la opción Autofila en un volumen, se consideran límites de capacidad según el tamaño máximo de volumen establecido por crecimiento automático, no según el tamaño del volumen original.



== Pasos

. En el panel de navegación izquierdo, haga clic en *Configuración* > *umbrales de estado*.
. En la página *Configuración/umbrales de estado*, haga clic en *volúmenes*.
. Configurar los valores de umbral adecuados para la capacidad, las copias Snapshot, las cuotas de qtree, el crecimiento de volumen y los inodos.
. Haga clic en *Guardar*.

