---
permalink: health-checker/task-restoring-data-using-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: Es posible restaurar archivos, directorios o un volumen entero sobrescritos o eliminados de una copia Snapshot con la función de restauración en la página de detalles Health/Volume. 
---
= Restaurar datos mediante la página de detalles Health/Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible restaurar archivos, directorios o un volumen entero sobrescritos o eliminados de una copia Snapshot con la función de restauración en la página de detalles Health/Volume.



== Antes de empezar

Debe tener el rol de administrador de OnCommand o de administrador del almacenamiento.



== Acerca de esta tarea

No puede restaurar flujos de archivos NTFS.

La opción de restauración no está disponible si:

* El ID de volumen es desconocido: Por ejemplo, cuando se mantiene una relación de interconexión de clústeres y el clúster de destino todavía no se detectó.
* El volumen es un volumen FlexGroup.
* El volumen está configurado para la replicación síncrona de SnapMirror.




== Pasos

. En la ficha *Protección* de la página de detalles *Estado/volumen*, haga clic con el botón derecho del ratón en la vista de topología el nombre del volumen que desea restaurar.
. Seleccione *Restaurar* en el menú.
+
También puede seleccionar *Restaurar* en el menú *acciones* para proteger el volumen actual para el que está viendo los detalles.

+
Aparece el cuadro de diálogo Restaurar.

. Seleccione el volumen y la copia Snapshot de los que desea restaurar datos si es diferente de la predeterminada.
. Seleccione los elementos que desea restaurar.
+
Es posible restaurar todo el volumen, o bien especificar carpetas y archivos que se desean restaurar.

. Seleccione la ubicación a la que desea restaurar los elementos seleccionados: *Ubicación original* o *ubicación alternativa existente*.
. Si selecciona una ubicación existente alternativa, realice una de las siguientes acciones:
+
** En el campo de texto Restaurar ruta, escriba la ruta de acceso de la ubicación en la que desea restaurar los datos y, a continuación, haga clic en *Seleccionar directorio*.
** Haga clic en *examinar* para abrir el cuadro de diálogo examinar directorios y siga los pasos siguientes:
+
... Seleccione el clúster, la SVM y el volumen a los que desea restaurar.
... En la tabla Nombre, seleccione un nombre de directorio.
... Haga clic en *Seleccionar directorio*.




. Haga clic en *Restaurar*.
+
Se inicia el proceso de restauración.

+
[NOTE]
====
Si se produce un error en una operación de restauración entre clústeres de alta disponibilidad de Cloud Volumes ONTAP y un error NDMP, es posible que deba añadir una ruta AWS explícita en el clúster de destino para que el destino pueda comunicarse con la LIF de gestión de clústeres del sistema de origen. Puede realizar este paso de configuración mediante Cloud Manager de OnCommand.

====

