---
permalink: install/reference-red-hat-and-centos-software-and-installation-requirements.html 
sidebar: sidebar 
keywords:  
summary: El sistema Linux en el que instala Unified Manager requiere versiones específicas del sistema operativo y del software compatible. 
---
= Requisitos de instalación y software de Red Hat Enterprise Linux y CentOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema Linux en el que instala Unified Manager requiere versiones específicas del sistema operativo y del software compatible.



== Software del sistema operativo

El sistema Linux debe tener instaladas las siguientes versiones del sistema operativo y el software de soporte:

* Red Hat Enterprise Linux o CentOS 64 bits versión 7.x
+
No se admite Red Hat Enterprise Linux 6.x a partir de Unified Manager 9.4.



Consulte la matriz de interoperabilidad para ver la lista completa y más actualizada de las versiones compatibles de Red Hat Enterprise Linux y CentOS.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"]

Se requieren los siguientes paquetes de terceros:

* MySQL Community Edition versión 5.7.23 o versiones posteriores de la familia 5.7 (del repositorio de MySQL)
* OpenJDK versión 11 (del repositorio de Red Hat Extra Enterprise Linux Server)
+
[NOTE]
====
Oracle Java no es compatible a partir de Unified Manager 9.5.

====
* P7zip versión 16.02 o posterior (del repositorio de Red Hat Extra Packages para Enterprise Linux)


[NOTE]
====
Si planea actualizar alguno de los programas de terceros después de que Unified Manager se haya ejecutado, primero debe apagar Unified Manager. Tras completar la instalación del software de terceros, puede reiniciar Unified Manager.

====


== Requisitos de autorización de usuarios

La instalación de Unified Manager en un sistema Red Hat Enterprise Linux o CentOS puede realizarse por el usuario raíz o por usuarios que no son raíz mediante el `sudo` comando.



== Requisitos de instalación

Las mejores prácticas para instalar Red Hat Enterprise Linux o CentOS y los repositorios asociados en su sistema son las siguientes:

* Debe instalar Red Hat Enterprise Linux o CentOS de acuerdo con las mejores prácticas de Red Hat y debe seleccionar las siguientes opciones predeterminadas, lo que requiere seleccionar "servidor con GUI".
* Durante la instalación de Unified Manager en Red Hat Enterprise Linux o CentOS, el sistema debe tener acceso al repositorio adecuado para que el programa de instalación pueda acceder a todas las dependencias de software necesarias e instalarlas.
* Para la `yum` Instalador para buscar software dependiente en los repositorios de Red Hat Enterprise Linux, debe haber registrado el sistema durante la instalación de Red Hat Enterprise Linux o después mediante una suscripción válida a Red Hat.
+
Consulte la documentación de Red Hat para obtener información acerca de Red Hat Subscription Manager.

* Debe habilitar el repositorio de paquetes adicionales para Enterprise Linux (EPEL) para instalar correctamente las utilidades de terceros necesarias en el sistema.
+
Si el repositorio de EPEL no está configurado en su sistema, debe descargar y configurar manualmente el repositorio.

+
xref:task-manually-configuring-the-epel-repository.adoc[Configurar manualmente el repositorio de EPEL]

* Si no está instalada la versión correcta de MySQL, debe habilitar el repositorio de MySQL para que pueda instalar correctamente el software MySQL en el sistema.
+
Si el repositorio de MySQL no está configurado en el sistema, debe descargar y configurar manualmente el repositorio.

+
xref:task-manually-configuring-the-mysql-repository.adoc[Configurar manualmente el repositorio de MySQL]



Si su sistema no tiene acceso a Internet y los repositorios no se duplican desde un sistema conectado a Internet al sistema no conectado, siga las instrucciones de instalación para determinar las dependencias de software externo de su sistema. A continuación, puede descargar el software necesario en el sistema conectado a Internet y copiar el `.rpm` Archivos en el sistema en el que tiene pensado instalar Unified Manager. Para descargar los artefactos y paquetes, debe usar `yum install` comando. Debe asegurarse de que los dos sistemas ejecutan la misma versión del sistema operativo y de que la licencia de suscripción es para la versión adecuada de Red Hat Enterprise Linux o CentOS.

[NOTE]
====
No debe instalar el software de terceros necesario desde repositorios distintos a los que se enumeran aquí. El software instalado desde los repositorios de Red Hat se ha diseñado explícitamente para Red Hat Enterprise Linux y cumple con las prácticas recomendadas de Red Hat (diseños de directorios, permisos, etc.). Es posible que el software desde otras ubicaciones no siga estas directrices, lo que puede provocar errores en la instalación de Unified Manager o podría provocar problemas con actualizaciones futuras.

====


== Requisito del puerto 443

Las imágenes genéricas de Red Hat y CentOS bloquean el acceso externo al puerto 443. Si su navegador no puede conectarse a su producto OnCommand, puede que este sea el problema. El siguiente comando habilita el acceso al puerto 443 para todos los usuarios y aplicaciones externos: `# firewall-cmd –zone=public –add-port=443/tcp –permanent; firewall-cmd –reload`

Consulte con su departamento DE TI antes de ejecutar este comando para ver si sus políticas de seguridad requieren un procedimiento diferente.
