---
permalink: install/task-changing-the-jboss-password.html 
sidebar: sidebar 
keywords:  
summary: Puede crear una nueva contraseña de JBoss personalizada para sobrescribir la contraseña predeterminada que se establece durante la instalación. Esta tarea es opcional, pero algunos sitios pueden requerir que esta funcionalidad de seguridad anule la configuración predeterminada de la instalación de Unified Manager. Esta operación también cambia la contraseña que JBoss utiliza para acceder a MySQL. 
---
= Cambio de la contraseña de JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear una nueva contraseña de JBoss personalizada para sobrescribir la contraseña predeterminada que se establece durante la instalación. Esta tarea es opcional, pero algunos sitios pueden requerir que esta funcionalidad de seguridad anule la configuración predeterminada de la instalación de Unified Manager. Esta operación también cambia la contraseña que JBoss utiliza para acceder a MySQL.



== Antes de empezar

* Debe tener acceso de usuario raíz al sistema Red Hat Enterprise Linux o CentOS en el que está instalado Unified Manager.
* Debe poder acceder a la información proporcionada por NetApp `password.sh` script en el directorio `/opt/netapp/essentials/bin`.




== Pasos

. Inicie sesión como usuario root en el sistema.
. Detenga los servicios de Unified Manager introduciendo los siguientes comandos en el orden mostrado: `service ocieau stop``service ocie stop`
+
No detenga el software MySQL asociado.

. Introduzca el siguiente comando para iniciar el proceso de cambio de contraseña: `/opt/netapp/essentials/bin/password.sh resetJBossPassword`
. Cuando se le solicite, introduzca la contraseña antigua de JBoss.
+
La contraseña predeterminada es `D11h1aMu@79%`.

. Cuando se le solicite, introduzca la nueva contraseña de JBoss y, a continuación, introdúzcala una segunda vez para confirmarla.
. Una vez finalizado el script, inicie los servicios de Unified Manager introduciendo los siguientes comandos en el orden que se muestra: `service ocie start``service ocieau start`
. Después de iniciar todos los servicios, puede iniciar sesión en la interfaz de usuario de Unified Manager.

