---
permalink: install/task-upgrading-mysql-on-linux.html 
sidebar: sidebar 
keywords:  
summary: Puede realizar una actualización a una versión más reciente de MySQL en el servidor Linux en el que está instalado Unified Manager para obtener soluciones frente a vulnerabilidades de seguridad. 
---
= Actualizar MySQL en Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar una actualización a una versión más reciente de MySQL en el servidor Linux en el que está instalado Unified Manager para obtener soluciones frente a vulnerabilidades de seguridad.



== Antes de empezar

Debe tener privilegios de usuario raíz para el sistema Linux en el que está instalado Unified Manager.



== Acerca de esta tarea

Sólo puede actualizar a actualizaciones secundarias de MySQL 5.7, por ejemplo, 5.7.1 a 5.7.2 . Por ejemplo, la versión 5.8 de no puede actualizarse a las versiones principales de MySQL.



== Pasos

. Inicie sesión como usuario raíz en el equipo host de Unified Manager.
. Descargue la versión más reciente de MySQL Community Server `.rpm` paquete en el sistema de destino.
. Destar el paquete a un directorio del sistema de destino.
. Obtendrá varias `.rpm` Paquetes en el directorio después de anular el paquete, pero Unified Manager solo necesita los siguientes paquetes rpm:
+
** mysql-community-client-5.7.x.
** mysql-community-libs-5.7.x.
** mysql-community-server-5.7.x.
** mysql-community-common-5.7.x.
** mysql-community-libs-compat-5.7.x Eliminar el resto `.rpm` paquetes. La instalación de todos los paquetes en un paquete de RPM no causará ningún problema.


. Detenga el servicio Unified Manager y el software MySQL asociado en el orden que se muestra:
. Invoque la actualización de MySQL mediante el siguiente comando: `yum install *.rpm`
+
`*.rpm` hace referencia a la `.rpm` Paquetes en el directorio en el que descargó la versión más reciente de MySQL.

. Inicie Unified Manager en el orden mostrado:

