---
permalink: install/task-restarting-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: Es posible que tenga que reiniciar Unified Manager después de realizar cambios de configuración. 
---
= Reinicio de Unified Manager en Red Hat Enterprise Linux o CentOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que tenga que reiniciar Unified Manager después de realizar cambios de configuración.



== Antes de empezar

Debe tener acceso de usuario raíz al servidor Red Hat Enterprise Linux o CentOS en el que está instalado Unified Manager.



== Pasos

. Inicie sesión como usuario raíz en el servidor en el que desea reiniciar el servicio Unified Manager.
. Detenga el servicio Unified Manager y el software MySQL asociado en el orden que se muestra:
+
Una vez instalada en una configuración de alta disponibilidad, detenga el servicio Unified Manager usando los comandos VCS Operations Manager o VCS.

. Inicie Unified Manager en el orden mostrado:
+
Una vez instalada en una configuración de alta disponibilidad, inicie el servicio de Unified Manager usando los comandos VCS Operations Manager o VCS.


